### ISSUE TITLE
The report box pops up twice

### ISSUE THREAD

**Issue by asgerv** [faceit-enhancer/faceit-enhancer#18] opened 2018-06-28 20:01 UTC
When you report someone, and select either Toxic, Afk, Verbal or Cheat, a new and similar popup box shows in the top left corner, where the latter needs to be chosen again, before you get to the popup where you can enter text and finalize the report.

Chrome 67 on Windows 10

**Comment by JussiRoos** [comment] 2019-02-08 00:25
Exactly what I'm experiencing. Still not fixed in version **1.7.4** (over half year later).

**Comment by poacher2k** [comment] 2019-02-16 17:52
This is caused by the "Hide player controls"-feature removing the parent of the popup, thereby making the next relative parent be such that it is placed in the top left corner. 

@JussiRoos : we accept both help with debugging and PRs :)

**Closed** 2019-05-20 06:34 UTC
Labels: bug
